#@TYPE: Machine
#@NAME: IPQ54xx_64 machine
#@DESCRIPTION: ipq54xx_64

include conf/machine/include/ipq-base.inc
include conf/machine/include/ipq-modules.inc
include conf/machine/include/arm/armv8a/tune-cortexa72.inc

DEFAULTTUNE = "aarch64"
TARGET_ARCH = "aarch64"
KARCH = "arm64"
DTB_PATH = 'qcom'
SOC_FAMILY = "ipq:ipq54xx_64"
NUM_RADIOS = "radios:3"

MACHINE_FEATURES += "usbhost"

RDEPENDS_${KERNEL_PACKAGE_NAME}-base = ""
PREFERRED_PROVIDER_virtual/kernel ?= "linux-ipq"
PREFERRED_VERSION_lua-native = "5.4.4"
BBMASK .= "|meta-rdk-ext/recipes-connectivity/openssl/openssl_3.0.5.bbappend"

DISTRO_FEATURES:append = " systemd "
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

UBOOT_MACHINE = "ipq5424_norplusnand_defconfig"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-2025"
PREFERRED_PROVIDER_u-boot ?= "u-boot-2025"
EXTRA_IMAGEDEPENDS += "u-boot-2025"

LINUX_VERSION ?= "6.6"

NITRAMFS_IMAGE_BUNDLE="1"
KERNEL_IMAGETYPE = "Image"

KERNEL_LOADADDR="0x80000000"
KERNEL_DEVICETREE ="ipq5424-rdp464.dtb \
		    ipq5424-rdp464-c2.dtb \
		    ipq5424-rdp496.dtb \
		    ipq5424-rdp466.dtb \
		    ipq5424-rdp466-c2.dtb \
		    ipq5424-rdp466-c3.dtb \
		    ipq5424-rdp466-rffe.dtb \
		    ipq5424-rdp485.dtb \
		    ipq5424-rdp485-c2.dtb \
		    ipq5424-rdp485-c3.dtb \
		    ipq5424-rdp485-rffe.dtb \
		    ipq5424-rdp487.dtb \
		    ipq5424-db-mr01.1.dtb \
"
CONF_VERSION = "2"
SERIAL_CONSOLE = "115200 ttyMSM0"
