#@TYPE: Machine
#@NAME: IPQ53xX machine
#@DESCRIPTION: ipq53xx

include conf/machine/include/ipq-base.inc
include conf/machine/include/ipq-modules.inc

SOC_FAMILY = "ipq:ipq53xx"

MACHINE_FEATURES += "usbhost"

RDEPENDS_${KERNEL_PACKAGE_NAME}-base = ""
PREFERRED_PROVIDER_virtual/kernel ?= "linux-ipq"
PREFERRED_VERSION_lua-native = "5.4.4"
BBMASK .= "|meta-rdk-ext/recipes-connectivity/openssl/openssl_3.0.5.bbappend"

DISTRO_FEATURES:append = " systemd "
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"

UBOOT_MACHINE = "ipq5332_norplusnand32_defconfig"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-2023"
PREFERRED_PROVIDER_u-boot ?= "u-boot-2023"
EXTRA_IMAGEDEPENDS += "u-boot-2023"

LINUX_VERSION ?= "6.6"

NITRAMFS_IMAGE_BUNDLE="1"
KERNEL_IMAGETYPE = "Image"
DTB_PATH = 'qcom'

KERNEL_LOADADDR="0x40000000"
KERNEL_DEVICETREE = "ipq5332-rdp441.dtb \
		     ipq5332-rdp442.dtb \
		     ipq5332-rdp446.dtb \
		     ipq5332-rdp468.dtb \
		     ipq5332-rdp472.dtb \
		     ipq5332-rdp473.dtb \
		     ipq5332-rdp474.dtb \
		     ipq5332-rdp477.dtb \
		     ipq5332-rdp478.dtb \
		     ipq5332-rdp479.dtb \
		     ipq5332-rdp480.dtb \
		     ipq5332-rdp481.dtb \
		     ipq5332-rdp483.dtb \
		     ipq5332-rdp484.dtb \
		     ipq5332-rdp486.dtb \
                    "
CONF_VERSION = "2"
SERIAL_CONSOLE = "115200 ttyMSM0"
